### ISSUE TITLE
Calls tag on page change even without init

### ISSUE THREAD

**Issue by WillSquire** [jelleklaver/react-linkedin-insight#33]
I’ve wrapped all usage in `if (LinkedInTag.verifyInit())`, but it still pops up with `[linkedin-insight-tag] LinkedIn Insight Tag not initialized. Before using, call LinkedInTag.init with required params` on each page change. I think the package is calling it without checking it’s initialised.

I would expect it not to show this message when un-initialised.

**Comment by jelleklaver** [comment]
Hi @WillSquire, sorry for responding this late. I was off for a holiday. 

The `verifyInit` will actually log this warning since it's used to check whether initialization has happened properly. It is currently not designed to be used without being initialized. 

Is there a reason you want to use `track` without it being initialized? You can call `init` with `disabled` as true if you don't want to use it. Would that be a proper solution for your use-case?
